### ISSUE TITLE
Docker Desktop - ImagePullBackOff for mlrun-kit-jupyter, version 1.0.3

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#2052]
Hi, I tried to install mlrun to docker desktop see sequence:

- [mlrun-install.bat.txt](https://github.com/mlrun/mlrun/files/8916274/mlrun-install.bat.txt)
- duration 30 minutes and it generate timeout (the issue is not slow network, but probably image issues)

content of docker image:

- ![mlrun-version](https://user-images.githubusercontent.com/95856749/174006425-b7965848-ec7e-43f7-9759-5f03b195e957.png)

view to status during installation:

- ![mlrun-kit-jupyter-ImagePullackOff](https://user-images.githubusercontent.com/95856749/174006525-cac7f882-2649-4224-9dd3-6a02df19a70a.png)

BTW:  I got the same result in case of installation 

- mlrun.ui.image.tag=1.0.2
- mlrun.api.image.tag=1.0.2 
- jupyterNotebook.image.tag=1.0.2

Thanks for help

**Comment by Tankilevitch** [comment]
Hey @george0st,
Can you please provide the pod logs? `kubectl -n mlrun describe pod <jupyter-pod>`.
Also can you try running `docker pull quay.io/mlrun/jupyter:1.0.3` and attach what you receive?

**Comment by george0st** [comment]
Logs see

- [jupyterpod.txt](https://github.com/mlrun/mlrun/files/8919158/jupyterpod.txt)

after run `docker pull quay.io/mlrun/jupyter:1.0.3` the installation process was successfully finished, see

- ![new](https://user-images.githubusercontent.com/95856749/174079261-932ee592-2dd8-45ee-b2cb-f462c707a1ac.png)

It seems that standard install steps (without running `docker pull quay.io/mlrun/jupyter:1.0.3`) had issue.

My problem was solved, many thanks.

**Comment by harishgawade1999** [comment]
> @Tankilevitch, logs see
> 
> * [jupyterpod.txt](https://github.com/mlrun/mlrun/files/8919158/jupyterpod.txt)
> 
> after run `docker pull quay.io/mlrun/jupyter:1.0.3` the installation process was successfully finished, see
> 
> * ![new](https://user-images.githubusercontent.com/95856749/174079261-932ee592-2dd8-45ee-b2cb-f462c707a1ac.png)
> 
> It seems that standard install steps (without running `docker pull quay.io/mlrun/jupyter:1.0.3`) had issue.
> 
> My problem was solved, many thanks.

how u solved ur problem sir? as im still getting same error. please help me. I'm working on this since last month. still getting same error.
